name: sur-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40

modules:
  - type: files
    files:
      - source: system
        destination: /

  - from-file: packages.yaml

  - type: akmods
    install:
      - v4l2loopback

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - NerdFontsSymbolsOnly

  - type: systemd
    system:
      enabled:
        - libvirtd.service

  - from-file: flatpaks.yaml
  - from-file: gnome-extensions.yaml

  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: signing
