name: sur-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - vscode.repo
    keys:
      - https://packages.microsoft.com/keys/microsoft.asc
    install:
      - starship
      - yad
      - dialog
      - podman-compose
      - virt-install
      - virt-manager
      - code
      - direnv
      - yt-dlp
      - hunspell
      - python3-pip
      - https://h30326.www3.hpe.com/hpn/via-4.7.0.2404092-rpm.x86_64.rpm?merchantId=ASP_DROPBOX
      - https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm
    remove:
      - firefox
      - firefox-langpacks

  # - type: bling
  #   install:
  #     - ublue-update

  - type: akmods
    install:
      - v4l2loopback

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - NerdFontsSymbolsOnly

  - type: systemd
    system:
      enabled:
        - libvirtd.service

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.gnome.FileRoller
        - app.devsuite.Ptyxis
        - com.bitwarden.desktop
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - com.usebottles.bottles
        - io.github.celluloid_player.Celluloid
        - io.github.peazip.PeaZip
        - org.chromium.Chromium
        - org.gnome.TextEditor
        - org.gnome.baobab # Disk usage
        - org.gnome.Calculator

  #- type: gnome-extensions
  #  install:
  #    - 3193 # Blur my Shell
  #    - 615  # AppIndicator and KStatusNotifierItem Support
  #    - 307  # Dash to Dock
  #    - 5489 # Search Light
  #    - 1319 # GSConnect

  - type: signing
