name: sur-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - vscode.repo
    keys:
      - https://packages.microsoft.com/keys/microsoft.asc
    install:
      - starship
      - yad
      - dialog
      - podman-compose
      - virt-install
      - virt-manager
      - code
      - direnv
      - yt-dlp
    remove:
      - firefox
      - firefox-langpacks

  # - type: bling
  #   install:
  #     - ublue-update

  - type: akmods
    install:
      - v4l2loopback

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - NerdFontsSymbolsOnly

  - type: systemd
    system:
      enabled:
        - libvirtd.service

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.gnome.FileRoller
        - app.devsuite.Ptyxis
        - com.bitwarden.desktop
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - com.usebottles.bottles
        - io.github.celluloid_player.Celluloid
        - io.github.peazip.PeaZip
        - org.chromium.Chromium
        - org.gnome.TextEditor
        - org.gnome.baobab # Disk usage
        - org.gnome.Calculator

  - type: gnome-extensions
    install:
      - 3193 # Blur my Shell
      - 615  # AppIndicator and KStatusNotifierItem Support
      - 307  # Dash to Dock
      - 5489 # Search Light

  - type: signing
