---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: sur-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - bieszczaders/kernel-cachyos-addons
        - yalter/niri
        - ulysg/xwayland-satellite
        - erikreider/SwayNotificationCenter
      nonfree: rpmfusion
    install:
      packages:
        - starship
        - yad
        - dialog
        - podman-compose
        - virt-install
        - virt-manager
        - direnv
        - yt-dlp
        - python3-pip
        - tailscale
        - scx-scheds
        - podman-docker
        - gnome-shell-extension-appindicator
        - lm_sensors
        - https://h30326.www3.hpe.com/hpn/via-4.7.0.2404092-rpm.x86_64.rpm?merchantId=ASP_DROPBOX
        # - niri
        # - fuzzel
        # - SwayNotificationCenter
        # - waybar
        # - swaybg
        # - xwayland-satellite
        # - swayidle
        # - swaylock
        # - brightnessctl
        - pavucontrol
        # - nm-applet
        # - wdisplays
        - libglvnd-gles
        # - blueman
    remove:
      packages:
        - firefox
        - firefox-langpacks

  # - type: rpm-ostree
  #   install:
  #     - zerotier-one

  # - type: bling
  #   install:
  #     - ublue-update

  # - type: akmods
  #   install:
  #     - v4l2loopback

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - NerdFontsSymbolsOnly

  - type: systemd
    system:
      enabled:
        - libvirtd.service
        - scx_loader.service
    user:
      enabled:
        - podman.service

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.gnome.FileRoller
        - com.bitwarden.desktop
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - com.usebottles.bottles
        - io.github.celluloid_player.Celluloid
        - io.github.peazip.PeaZip
        - org.chromium.Chromium
        - org.gnome.TextEditor
        - org.gnome.baobab # Disk usage
        - org.gnome.Calculator
        - dev.qwery.AddWater # GUI for installing Firefox Adwaita theme
        - io.github.dvlv.boxbuddyrs
        - org.gnome.Loupe # Image viewer
        - dev.vencord.Vesktop
        - com.visualstudio.code

  - type: gnome-extensions
    install:
      - 3193 # Blur my Shell
      # - 615 # AppIndicator and KStatusNotifierItem Support
      - 307 # Dash to Dock
      - 1319 # GSConnect
      - 6099 # PaperWM

  - type: justfiles
    include:
      - hm-update.just

  - type: signing
